name: Contributors

on:
  schedule:
    - cron: '0/10 * * * *'
  push:
    branches:
      - main

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/contributors-list@v1
        name: contributors-doocs-leetcode
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          repo: doocs/leetcode
          svgPath: images/contributors-doocs-leetcode.svg
          round: true
          includeBots: true
